wandb_version: 1

hyperparameters:
  desc: null
  value:
    learning_rate: 0.001
    batch_size: 64
    num_epochs: 2
    image_size:
    - 224
    - 224
    num_channels: 1
    dropout_rate: 0.3
    kernel_size: 3
    stride: 2
    padding: 3
    labels_norm: 216
training:
  desc: null
  value:
    dataset_path: dataset/train/
    csv_file: train.csv
    image_folder: image/
    model_save_path: checkpoints/model.pth
    cuda: true
testing:
  desc: null
  value:
    dataset_path: dataset/train/
    csv_file: train.csv
    image_folder: image/
    model_save_path: checkpoints/model.pth
    cuda: true
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705706571.823599
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.2
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
